local Manager = require("bsi.cmd.manager")

describe("cmd manager", function()
  it("tracks new commands", function()
    local cmd = Manager.new({ "printf", "hello" })
    assert.is_not_nil(cmd)
    assert.is_not_nil(cmd.id)
    local tracked = Manager.get(cmd.id)
    assert.equals(cmd, tracked)
  end)

  it("lists all tracked commands", function()
    local c1 = Manager.new({ "printf", "a" })
    local c2 = Manager.new({ "printf", "b" })
    local list = Manager.list()
    assert.is_not_nil(list[c1.id])
    assert.is_not_nil(list[c2.id])
  end)

  it("filters by status", function()
    local c1 = Manager.new({ "true" })
    local c2 = Manager.new({ "sleep", "10" })
    vim.wait(3000, function() return Manager.get(c1.id):status() == "done" end)
    local done = Manager.by_status("done")
    assert.is_not_nil(done[c1.id])
    assert.is_nil(done[c2.id])
  end)

  it("removes command from tracking", function()
    local cmd = Manager.new({ "printf", "hello" })
    Manager.remove(cmd.id)
    assert.is_nil(Manager.get(cmd.id))
  end)

  it("disposes and removes command", function()
    local cmd = Manager.new({ "printf", "hello" })
    Manager.dispose(cmd.id)
    assert.is_nil(Manager.get(cmd.id))
  end)

  it("cleans up finished commands", function()
    local c1 = Manager.new({ "true" })
    local c2 = Manager.new({ "false" })
    vim.wait(3000, function()
      local s1 = Manager.get(c1.id):status()
      local s2 = Manager.get(c2.id):status()
      return s1 ~= "running" and s2 ~= "running"
    end)
    assert.is_true(Manager.get(c1.id):status() ~= "running")
    assert.is_true(Manager.get(c2.id):status() ~= "running")
    Manager.cleanup()
    assert.is_nil(Manager.get(c1.id))
    assert.is_nil(Manager.get(c2.id))
  end)

  it("keeps running commands during cleanup", function()
    local cmd = Manager.new({ "sleep", "10" })
    Manager.cleanup()
    assert.is_not_nil(Manager.get(cmd.id))
  end)
end)

