local numstat = require("bsi.git.numstat")

describe("bsi.git.numstat", function()
  it("parses added and deleted counts to absolute paths", function()
    local map = numstat.parse("23\t23\tsrc/a.lua\n1\t0\tb.lua\n", "/repo")
    assert.are.same({ added = 23, deleted = 23 }, map["/repo/src/a.lua"])
    assert.are.same({ added = 1, deleted = 0 }, map["/repo/b.lua"])
  end)

  it("treats binary dashes as zero", function()
    local map = numstat.parse("-\t-\tpic.png\n", "/repo")
    assert.are.same({ added = 0, deleted = 0 }, map["/repo/pic.png"])
  end)

  it("merges staged and unstaged by summing", function()
    local unstaged = numstat.parse("10\t2\tfile.lua\n", "/repo")
    local staged = numstat.parse("13\t21\tfile.lua\n1\t0\tother.lua\n", "/repo")
    local map = numstat.merge(unstaged, staged)
    assert.are.same({ added = 23, deleted = 23 }, map["/repo/file.lua"])
    assert.are.same({ added = 1, deleted = 0 }, map["/repo/other.lua"])
  end)

  it("formats +N-M, +N, and -M", function()
    assert.equals(" +23-23", numstat.format(23, 23))
    assert.equals(" +7", numstat.format(7, 0))
    assert.equals(" -4", numstat.format(0, 4))
    assert.equals("", numstat.format(0, 0))
  end)
end)
